#!/bin/bash

source @sub_MRNETAPP_HOME@/etc/sourceme.sh

export TREE_DBSCAN_HOME=@sub_PREFIX@
export MRNAPP_FILTER_PATH=$TREE_DBSCAN_HOME/lib:$MRNAPP_FILTER_PATH
export LD_LIBRARY_PATH=@sub_MRNETAPP_LIBSDIR@:@sub_CLUSTERING_DYNAMIC_PATH@:@sub_CGAL_DYNAMIC_PATH@:$LD_LIBRARY_PATH

